# Site settings
title: Danyang Liu (刘丹阳)
general_email: danyliu@sjtu.edu.cn

description: > # this means to ignore newlines until "baseurl:"
   Final-year postgraduate student in School of Cyber Science and Engineering, SJTU. Passionate about research in Natural Language Processing.

baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://dyliu.me" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: github_username
linkedin_username: linkedin_username
facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
theme: jekyll-theme-cayman